# Generated by Django 2.0.1 on 2018-01-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RadioStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название (ru)')),
                ('name_en', models.CharField(max_length=100, verbose_name='Название (en)')),
                ('description', models.TextField(max_length=2000, verbose_name='Описание')),
                ('url_broadcasting', models.URLField(verbose_name='URL вещания')),
            ],
        ),
    ]
