# Generated by Django 2.0.1 on 2018-01-02 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='radiostation',
            options={'ordering': ['name'], 'verbose_name': 'Радиостанция', 'verbose_name_plural': 'Радиостанции'},
        ),
    ]
