# Generated by Django 2.0.1 on 2018-01-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0002_auto_20180102_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiostation',
            name='logo',
            field=models.ImageField(default='static/img/logo/default.png', upload_to='static/img/logo/'),
        ),
    ]
